### PR TITLE
Add a `Current Time` name that can be used to refer to the current time

### PR DESCRIPTION
**Pull request by Page-**
Change-type: minor

### CODE REVIEW

**Comment by Page-** [comment]
@balena-ci I self-certify!

**Comment by Page-** [comment]
@balena-ci retest

**Comment by thgreasi** [comment]
@Page- can I get a hint oh how to use this?
While I was able to write
```
Rule: It is necessary that each release that has an end timestamp, has a start timestamp that is before the end timestamp.
```
I was having issues defining something like:
```
Rule: It is necessary that each release that has an end timestamp, has a start timestamp that is before the Current Time.
```

**Comment by Page-** [comment]
@thgreasi you need the `(Type)` to specify the vocab it's from, ie `Current Time (Type)`

**Comment by thgreasi** [comment]
Thanks :pray:

**Comment by thgreasi** [comment]
I might still be missing something b/c the generated SQL that I got was:
```sql
-- It is necessary that each release has a start timestamp that is after the Current Time (Type).
SELECT NOT EXISTS (
	SELECT 1
	FROM "release" AS "release.0"
	WHERE NOT (
		"Date Time.undefined"."Current Time" < "release.0"."start timestamp"
		AND "release.0"."start timestamp" IS NOT NULL
	)
) AS "result";
```
With `"Date Time.undefined"`  erroring of course.

**Pull request merged**
